name: Arduino Compile to UF2

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Python Dependencies & Adafruit Tools
        run: |
          pip3 install pyserial adafruit-nrfutil

      - name: Install nRF52 Board Core
        run: |
          arduino-cli core update-index --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          arduino-cli core install adafruit:nrf52@1.7.0 --additional-urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json

      - name: Compile Code & Generate UF2
        run: |
          # Wir nutzen die FQBN und aktivieren über die Board-Optionen die automatische UF2-Erstellung
          REAL_FQBN="adafruit:nrf52:itsybitsy52840"
          
          echo "Kompiliere und erzeuge finale UF2-Datei..."
          
          arduino-cli compile --fqbn "$REAL_FQBN" \
            --build-property "compiler.cpp.extra_flags=-DSOFTDEVICE_PRESENT -DS340" \
            --build-property "compiler.c.extra_flags=-DSOFTDEVICE_PRESENT -DS340" \
            --output-dir ./build ./ANT2.ino

      - name: Upload UF2 Firmware
        uses: actions/upload-artifact@v4
        with:
          name: blipbox-v4-firmware
          path: ./build/
